2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_setup.py:_flush():68] Configure stats pid to 58757
2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_setup.py:_flush():68] Loading settings from /nfs/users/ext_group6/.config/wandb/settings
2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_setup.py:_flush():68] Loading settings from /nfs/users/ext_group6/Dana_Project/Balanced-Contrastive-Learning/wandb/settings
2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': '/nfs/users/ext_group6/Dana_Project/Balanced-Contrastive-Learning/main.py'}
2023-02-18 17:15:27,683 INFO    MainThread:58757 [wandb_init.py:_log_setup():492] Logging user logs to /nfs/users/ext_group6/Dana_Project/Balanced-Contrastive-Learning/wandb/run-20230218_171527-xhumotww/logs/debug.log
2023-02-18 17:15:27,684 INFO    MainThread:58757 [wandb_init.py:_log_setup():493] Logging internal logs to /nfs/users/ext_group6/Dana_Project/Balanced-Contrastive-Learning/wandb/run-20230218_171527-xhumotww/logs/debug-internal.log
2023-02-18 17:15:27,684 INFO    MainThread:58757 [wandb_init.py:init():532] calling init triggers
2023-02-18 17:15:27,684 INFO    MainThread:58757 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'architecture': 'resnet50', 'batch_size': 64, 'epochs': 90, 'learning_rate': 0.1, 'momentum': 0.9, 'schedule': [860, 880], 'weight_decay': 0.0005, 'temp': 0.07, 'alpha': 1.0, 'beta': 0.35, 'cl_views': 'sim-sim', 'seed': None, 'randaug': True, 'randaug_m': 10, 'randaug_n': 2, 'cos': True, 'use_norm': True, 'feat_dim': 1024, 'warmup_epochs': 0, 'gpu': None}
2023-02-18 17:15:27,684 INFO    MainThread:58757 [wandb_init.py:init():588] starting backend
2023-02-18 17:15:27,684 INFO    MainThread:58757 [wandb_init.py:init():592] setting up manager
2023-02-18 17:15:27,689 INFO    MainThread:58757 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-18 17:15:27,731 INFO    MainThread:58757 [wandb_init.py:init():599] backend started and connected
2023-02-18 17:15:27,738 INFO    MainThread:58757 [wandb_init.py:init():687] updated telemetry
2023-02-18 17:15:27,969 INFO    MainThread:58757 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-02-18 17:15:28,703 INFO    MainThread:58757 [wandb_run.py:_on_init():2134] communicating current version
2023-02-18 17:15:29,040 INFO    MainThread:58757 [wandb_run.py:_on_init():2143] got version response 
2023-02-18 17:15:29,040 INFO    MainThread:58757 [wandb_init.py:init():775] starting run threads in backend
2023-02-18 17:15:55,924 WARNING MainThread:58757 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 787, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/nfs/users/ext_group6/miniconda3/envs/BCL/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-02-18 17:16:17,179 WARNING MsgRouterThr:58757 [router.py:message_loop():77] message_loop has been closed
